name: Create GitHub Release

on:
  push:
    branches:
      - main

jobs:
  check-version:
    runs-on: ubuntu-latest
    outputs:
      version: ${{ steps.get-current-version.outputs.version }}
      should_release: ${{ steps.check-release.outputs.should_release }}
      
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0  # Fetch all history to ensure we can get all tags
      
      - name: Get current version from package.json
        id: get-current-version
        run: echo "version=$(node -p "require('./package.json').version")" >> $GITHUB_OUTPUT
      
      - name: Get latest release version
        id: get-latest-release
        uses: pozetroninc/github-action-get-latest-release@master
        with:
          repository: ${{ github.repository }}
          excludes: prerelease, draft
          fallback: 0.0.0  # Use fallback if no release exists yet
      
      - name: Compare versions
        id: check-release
        run: |
          # Remove the 'v' prefix if it exists in the latest release tag
          LATEST_VERSION=$(echo "${{ steps.get-latest-release.outputs.release }}" | sed 's/^v//')
          CURRENT_VERSION="${{ steps.get-current-version.outputs.version }}"
          
          echo "Latest released version: $LATEST_VERSION"
          echo "Current package.json version: $CURRENT_VERSION"
          
          # Check if versions are different and current is newer (using sort -V for version sorting)
          if [ "$LATEST_VERSION" != "$CURRENT_VERSION" ] && [ "$(printf '%s\n%s\n' "$LATEST_VERSION" "$CURRENT_VERSION" | sort -V | tail -n1)" = "$CURRENT_VERSION" ]; then
            echo "Current version is newer than latest release - will create a new release"
            echo "should_release=true" >> $GITHUB_OUTPUT
          else
            echo "No new version to release"
            echo "should_release=false" >> $GITHUB_OUTPUT
          fi

  build-and-release:
    needs: check-version
    if: needs.check-version.outputs.should_release == 'true'
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '16'
          
      - name: Install dependencies
        run: npm ci
      
      - name: Package Extension
        run: npx vsce package
        
      - name: Get VSIX path
        id: get-vsix-path
        run: echo "vsix_path=$(find . -maxdepth 1 -name "*.vsix" | head -n 1)" >> $GITHUB_OUTPUT
          
      - name: Create tag
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git tag -a v${{ needs.check-version.outputs.version }} -m "Release v${{ needs.check-version.outputs.version }}"
          git push origin v${{ needs.check-version.outputs.version }}
          
      - name: Create GitHub Release with auto-generated notes
        id: create_release
        uses: softprops/action-gh-release@v1
        with:
          tag_name: v${{ needs.check-version.outputs.version }}
          name: Release v${{ needs.check-version.outputs.version }}
          draft: false
          prerelease: false
          generate_release_notes: true
          files: ${{ steps.get-vsix-path.outputs.vsix_path }}