name: VS Code Extension Tests

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main]
  workflow_dispatch:  # Allow manual triggering

jobs:
  test:
    name: Test Extension
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [18.x]

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v3

    - name: Setup Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'

    - name: Install Dependencies
      run: npm ci
      
    - name: Lint
      run: npm run lint
      
    - name: Compile
      run: npm run compile
      
    - name: Setup Virtual Display
      run: |
        /usr/bin/Xvfb :99 -screen 0 1024x768x24 > /dev/null 2>&1 &
        echo "DISPLAY=:99" >> $GITHUB_ENV
        
    - name: Run Tests
      run: npm test

  
  build-aspect:
    name: Build Kotlin LSP Aspect
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - uses: bazel-contrib/setup-bazel@0.14.0
        with:
          bazelisk-cache: true

      - name: Build Aspect
        run: cd bazel/aspect && bazel build //lsp_info_extractor:lsp_info_extractor_deploy.jar


  build-aspect-bazel7:
    name: Build Kotlin LSP Aspect (Bazel 7)
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - uses: bazel-contrib/setup-bazel@0.14.0
        with:
          bazelisk-cache: true

      - name: Build Aspect (Bazel 7)
        run: cd bazel/aspect && USE_BAZEL_VERSION=7.4.1 bazel build //lsp_info_extractor:lsp_info_extractor_deploy.jar

  build-aspect-bazel6:
    name: Build Kotlin LSP Aspect (Bazel 6)
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - uses: bazel-contrib/setup-bazel@0.14.0
        with:
          bazelisk-cache: true

      - name: Build Aspect (Bazel 6)
        run: cd bazel/aspect && USE_BAZEL_VERSION=6.5.0 bazel build //lsp_info_extractor:lsp_info_extractor_deploy.jar

      